org: slasia
app: poc
service: poc-serverless-framework
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs20.x

functions:
  email-api:
    handler: dist/email-api/handler.handler
    events:
      - http:
          path: email/{proxy+}
          method: any 
          cors: true
  user-api:
    handler: dist/user-api/handler.handler
    events:
      - http:
          path: user/{proxy+}
          method: any 
          cors: true


plugins:
  - serverless-offline

custom:
  serverless-offline:
    httpPort: 3000