openapi: 3.0.0
components:
  schemas:
    TestUserModel:
      type: object
      properties:
        name:
          type: string
        surname:
          type: string
        address:
          type: string
        id:
          type: integer
  securitySchemes: {}
info:
  title: My Test API
  description: Test API
  version: 1.0.0
paths:
  /user/:
    get:
      operationId: user-api
      summary: get test users
      description: get detail test user
      responses:
        '200':
          description: detail user test
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TestUserModel'
