org: slasia
app: poc
service: lambda-services
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs20.x

package:
  individually: true
  excludeDevDependencies: true
  patterns:
    - '!**' 
    - 'dist/**' 
    - '!dist/**/*.map' 
    - '!dist/**/*.ts' 
    - '!node_modules/**' 
    - '!*.ts' 
    - '!*.yml' 
    - '!test/**' 
    - '!tests/**' 
    - '!*.md' 
    - '!*.json' 

functions:
  debug-api:
    handler: dist/debug/handler.handler
    events:
      - http:
          path: debug
          method: get
          cors: true

  email-api:
    handler: dist/email-api/handler.handler
    layers:
      - arn:aws:lambda:us-east-1:000000000000:layer:common:1
    events:
      - http:
          path: email
          method: get
          cors: true
      - http:
          path: email/{proxy+}
          method: any
          cors: true

  user-api:
    handler: dist/user-api/handler.handler
    layers:
      - arn:aws:lambda:us-east-1:000000000000:layer:common:1
    events:
      - http:
          path: user
          method: get
          cors: true
      - http:
          path: user/{proxy+}
          method: any
          cors: true

plugins:
  - serverless-localstack
  - serverless-offline
custom:
  localstack:
    stages:
      - local
    host: http://localhost
    edgePort: 4566
    autostart: true
