org: slasia
app: poc
service: lambda-services
useDotenv: true
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs20.x

environment:
   TYPEORM_CONNECTION: postgres
   TYPEORM_HOST: ${env:DB_HOST}
   TYPEORM_USERNAME: ${env:DB_USER}
   TYPEORM_PASSWORD: ${env:DB_PASSWORD}
   TYPEORM_DATABASE: ${env:DB_DATABASE}
   TYPEORM_PORT: ${env:DB_PORT}
   TYPEORM_SYNCHRONIZE: false
   TYPEORM_LOGGING: false
   TYPEORM_ENTITIES: dist/entity/**/*.js

package:
  individually: true
  excludeDevDependencies: true
  patterns:
    - '!**' 
    - 'dist/**' 
    - '!dist/**/*.map' 
    - '!dist/**/*.ts' 
    - 'node_modules/**' 
    - '!*.ts' 
    - '!*.yml' 
    - '!test/**' 
    - '!tests/**' 
    - '!*.md' 
    - '!*.json' 

functions:
  user-api:
    handler: dist/src/user-api/handler.handler
    events:
      - http:
          path: user/{proxy+}
          method: any
          cors: true

plugins:
  - serverless-offline
  - serverless-dotenv-plugin